server:
  port: 5000

spring:
  application:
    name: better-elk
  profiles:
    active: dev


  #ES 配置
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.2.11:9300
      #cluster-nodes: 106.12.187.16:9300
      repositories:
        enabled: true


knife4j:
  # 开启增强配置
  enable: true
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    username: mqz
    password: mengqizhang

swagger:
  enable: true

logging:
  config: classpath:logback/logback-@projectActive@.xml



# dev 环境
---
spring:
  profiles: dev

# prod 环境
---
spring:
  profiles: prod

