server:
  port: 5000

spring:
  application:
    name: better-elk
  profiles:
    active: dev


  #ES 配置
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.2.11:9300
      #cluster-nodes: 106.12.187.16:9300
      repositories:
        enabled: true


knife4j:
  # 开启增强配置
  enable: true
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    username: mqz
    password: mengqizhang

  setting:
    #自定义主页
    enableHomeCustom: true
    homeCustomLocation: classpath:resources/home/welcome.md

    #自定义footer
    enableFooter: true
    enableFooterCustom: true
    footerCustomContent: SuperNiuBI License 2.0 | Copyright  2019-[浙江大拿有限公司](https://gitee.com/DemoMeng)

swagger:
  enable: true

logging:
  config: classpath:logback/logback-@projectActive@.xml



# dev 环境
---
spring:
  profiles: dev

# prod 环境
---
spring:
  profiles: prod

