filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~


#日志文件作为数据涞源，注意如果是通过容器启动filebeat的话，这个日志路径是容器内的
filebeat.inputs:
  - type: log
    enabled: true
    paths: /var/share/filebeat/logs/info_2021-07-04.log
    tags: ["lowcode-log"]
    fields:
      fileType: lowcode-log
  - type: log
    enabled: true
    paths: /var/share/filebeat/logs/info_2021-07-04.log
    tags: ["gateway-log"]
    fields:
        fileType: gateway-log
### 新增一个tags区分不同的项目类型，然后logstash中直接根据tags判断输出成不同的索引
### 也可以使用fileds，注意取值方式 参考logstash中的配置



output.logstash:
  hosts: ["x.xx.xx.xx:5044"]

#输出到es
#output.elasticsearch:
#  hosts: ["es的ip:9200"]
#  index: "filebeat-%{+yyyy.MM.dd}"

# 鉴权可以暂时不用
## username: '${ELASTICSEARCH_USERNAME:}'
## password: '${ELASTICSEARCH_PASSWORD:}'
